// 0-4
const statusDb = [
  'Open for new games',
  'Looking for scholarships',
  'Seeking new friends',
  'Just chilling',
  'Do not disturb',
]
// 0-12
const tagDb = [
  'MMORPG',
  'FPS',
  'OPENWORLD',
  'RPG',
  'RTS',
  'MOBA',
  'SPG',
  'RAC',
  'ACT',
  'AVG',
  'SLG',
  'SIM',
  'EDU',
]
const avatarDb = [
  '1.png',
  '2.jpg',
  '3.png',
  '4.png',
  '5.png',
  '6.png',
  '7.png',
  '8.png',
  '9.png',
  '10.png',
  '11.png',
  '12.jpg',
  '13.png',
  '14.png',
  '15.png',
  '16.png',
  '17.png',
  '18.png',
  '19.png',
  '20.png',
  '21.png',
  '22.jpg',
  '23.png',
  '24.png',
  '25.png',
  '26.png',
  '27.png',
  '28.png',
  '29.png',
  '30.png',
]

export const bannerList = [
  {
    id: 1,
    name: 'Axie Infinity',
    logo: '/mock/game1/banner/logo_1.png',
    bg: '/mock/game/banner/bg_1.png',
    tokenLogo: '/mock/token/slp.png',
    tokenName: 'SLP',
    totalPrice: 10000,
    endTime: '2022-06-12 12:00:00',
    userList: [
      {
        id: 1,
        level: '1st',
        name: 'Arnt',
        avatar: '/mock/avatar/1.png',
        tokenEarned: 6788,
        roi: 231,
        scholar: 1500,
        scholarGuild: '/mock/guild/3.png',
      },
      {
        id: 2,
        level: '2nd',
        name: 'Tello',
        avatar: '/mock/avatar/2.jpg',
        tokenEarned: 6432,
        roi: 224,
        scholar: 1200,
        scholarGuild: '/mock/guild/1.png',
      },
      {
        id: 3,
        level: '3rd',
        name: 'Zoldyck',
        avatar: '/mock/avatar/3.png',
        tokenEarned: 6133,
        roi: 211,
        scholar: 1000,
      },
      {
        id: 4,
        level: '4th',
        name: 'austin',
        avatar: '/mock/avatar/4.png',
        tokenEarned: 5979,
        roi: 176,
        scholar: 800,
      },
      {
        id: 5,
        level: '5th',
        name: 'boeroe',
        avatar: '/mock/avatar/5.avif',
        tokenEarned: 5563,
        roi: 135,
        scholar: 500,
        scholarGuild: '/mock/guild/4.png',
      },
    ],
  },
  {
    id: 2,
    name: 'Stepn',
    logo: '/mock/game1/banner/logo_2.png',
    bg: '/mock/game/banner/bg_2.png',
    tokenLogo: '/mock/token/gst.webp',
    tokenName: 'GST',
    totalPrice: 25000,
    endTime: '2022-06-10 08:00:00',
    userList: [
      {
        id: 21,
        level: '1st',
        name: 'BADMAN',
        avatar: '/mock/avatar/6.avif',
        tokenEarned: 3258,
        roi: 271,
        scholar: 3000,
      },
      {
        id: 22,
        level: '2nd',
        name: 'cope',
        avatar: '/mock/avatar/7.gif',
        tokenEarned: 3219,
        roi: 266,
        scholar: 2500,
        scholarGuild: '/mock/guild/1.png',
      },
      {
        id: 23,
        level: '3rd',
        name: 'Miller',
        avatar: '/mock/avatar/8.png',
        tokenEarned: 3061,
        roi: 259,
        scholar: 2000,
      },
      {
        id: 24,
        level: '4th',
        name: 'Sim010',
        avatar: '/mock/avatar/9.avif',
        tokenEarned: 3005,
        roi: 244,
        scholar: 1800,
        scholarGuild: '/mock/guild/2.png',
      },
      {
        id: 25,
        level: '5th',
        name: 'E7',
        avatar: '/mock/avatar/10.avif',
        tokenEarned: 2999,
        roi: 231,
        scholar: 1600,
        scholarGuild: '/mock/guild/1.png',
      },
    ],
  },
  {
    id: 3,
    name: 'Let me speak',
    logo: '/mock/game1/banner/logo_3.png',
    bg: '/mock/game/banner/bg_3.png',
    tokenLogo: '/mock/token/ls.png',
    tokenName: 'LS',
    totalPrice: 80000,
    endTime: '2022-06-10 18:00:00',
    userList: [
      {
        id: 31,
        level: '1st',
        name: 'BADMAN',
        avatar: '/mock/avatar/11.avif',
        tokenEarned: 3258,
        roi: 271,
        scholar: 9000,
        scholarGuild: '/mock/guild/3.png',
      },
      {
        id: 32,
        level: '2nd',
        name: 'cope',
        avatar: '/mock/avatar/12.svg',
        tokenEarned: 3219,
        roi: 266,
        scholar: 8000,
      },
      {
        id: 33,
        level: '3rd',
        name: 'Miller',
        avatar: '/mock/avatar/13.png',
        tokenEarned: 3061,
        roi: 259,
        scholar: 7000,
        scholarGuild: '/mock/guild/4.png',
      },
      {
        id: 34,
        level: '4th',
        name: 'Sim010',
        avatar: '/mock/avatar/14.avif',
        tokenEarned: 3005,
        roi: 244,
        scholar: 5000,
      },
      {
        id: 35,
        level: '5th',
        name: 'E7',
        avatar: '/mock/avatar/15.png',
        tokenEarned: 2999,
        roi: 209,
        scholar: 3000,
      },
    ],
  },
]

export const playerList = [
  {
    name: '0xCryptor',
    avatar: '/pics/avatar/16.png',
    roi: 271,
    badge: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
    states: statusDb[1],
    tags: [tagDb[2], tagDb[1], tagDb[3]],
  },
  {
    name: 'Christ',
    avatar: '/pics/avatar/17.png',
    roi: 271,
    badge: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
    states: statusDb[1],
    tags: [tagDb[12], tagDb[11]],
  },
  {
    name: 'Cliff',
    avatar: '/pics/avatar/18.png',
    roi: 271,
    badge: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
    states: statusDb[2],
    tags: [tagDb[3], tagDb[5], tagDb[6]],
  },
  {
    name: 'Dimok',
    avatar: '/pics/avatar/19.png',
    roi: 271,
    badge: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
    states: statusDb[3],
    tags: [tagDb[4], tagDb[5], tagDb[7]],
  },
  {
    name: 'DKOB',
    avatar: '/pics/avatar/20.png',
    roi: 271,
    badge: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
    states: statusDb[4],
    tags: [tagDb[2], tagDb[8], tagDb[9]],
  },
  {
    name: 'Guinox',
    avatar: '/pics/avatar/21.png',
    roi: 271,
    badge: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
    states: statusDb[3],
    tags: [tagDb[10], tagDb[2], tagDb[11]],
  },
  {
    name: 'harryho',
    avatar: '/pics/avatar/22.png',
    roi: 271,
    badge: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
    states: statusDb[2],
    tags: [tagDb[4], tagDb[9], tagDb[6]],
  },
  {
    name: 'Kustinski',
    avatar: '/pics/avatar/23.png',
    roi: 271,
    badge: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
    states: statusDb[4],
    tags: [tagDb[3], tagDb[6], tagDb[1]],
  },
]

export const playerList1 = [
  {
    id: 1,
    avatar: '/mock/player/1.png',
    name: 'Maximo YrysnkYrysnkYrysnk',
    roi: 134,
    tags: ['stable coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 2,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 3,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 4,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 5,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 6,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 7,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 8,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
]

export const reviewList = [
  {
    id: 1,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/1.png',
    userAvatar: '/mock/avatar/1.png',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
  {
    id: 2,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/3.png',
    userAvatar: '/mock/avatar/1.png',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
  {
    id: 3,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/1.png',
    userAvatar: '/mock/avatar/3.png',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
  {
    id: 4,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/2.png',
    userAvatar: '/mock/avatar/1.png',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
  {
    id: 5,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/1.png',
    userAvatar: '/mock/avatar/1.png',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
  {
    id: 6,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/1.png',
    userAvatar: '/mock/avatar/2.avif',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
]
