// 0-4
const statusDb = [
  'Open for new games',
  'Looking for scholarships',
  'Seeking new friends',
  'Just chilling',
  'Do not disturb',
]
// 0-12
const tagDb = [
  'MMORPG',
  'FPS',
  'OPENWORLD',
  'RPG',
  'RTS',
  'MOBA',
  'SPG',
  'RAC',
  'ACT',
  'AVG',
  'SLG',
  'SIM',
  'EDU',
]
export const avatarDb = [
  '1.png',
  '2.jpg',
  '3.png',
  '4.png',
  '5.avif',
  '6.avif',
  '7.gif',
  '8.png',
  '9.avif',
  '10.avif',
  '11.avif',
  '12.svg',
  '13.png',
  '14.avif',
  '15.png',
  '16.avif',
  '17.png',
  '18.avif',
  '19.avif',
  '20.png',
  '21.png',
  '22.png',
  '23.gif',
  '24.png',
  '25.png',
  '26.avif',
  '27.png',
  '28.png',
  '29.gif',
  '30.png',
  '31.avif',
  '32.avif',
  '33.avif',
  '34.png',
  '35.gif',
  '36.gif',
  '37.svg',
  '38.png',
  '39.png',
  '40.png',
  '41.svg',
  '42.png',
  '43.png',
  '44.png',
  '45.png',
  '46.avif',
  '47.png',
  '48.png',
  '49.png',
  '50.png',
  '51.png',
  '52.gif',
  '53.gif',
  '54.gif',
  '55.png',
  '56.png',
]
const getAvatar = (id) => {
  return `/mock/avatar/${avatarDb[id - 1]}`
}
export const avatarList = avatarDb.map(x => `/mock/avatar/${x}`)
export const bannerList = [
  {
    id: 1,
    name: 'Axie Infinity',
    logo: '/mock/game1/banner/logo_1.png',
    bg: '/mock/game/banner/bg_1.png',
    tokenLogo: '/mock/token/slp.png',
    tokenName: 'SLP',
    totalPrice: 10000,
    endTime: '2022-06-12 12:00:00',
    userList: [
      {
        id: 1,
        level: '1st',
        name: 'Arnt',
        avatar: getAvatar(1),
        tokenEarned: 6788,
        roi: 231,
        scholar: 1500,
        scholarGuild: '/mock/guild/3.png',
      },
      {
        id: 2,
        level: '2nd',
        name: 'Tello',
        avatar: getAvatar(2),
        tokenEarned: 6432,
        roi: 224,
        scholar: 1200,
        scholarGuild: '/mock/guild/1.png',
      },
      {
        id: 3,
        level: '3rd',
        name: 'Zoldyck',
        avatar: getAvatar(3),
        tokenEarned: 6133,
        roi: 211,
        scholar: 1000,
      },
      {
        id: 4,
        level: '4th',
        name: 'austin',
        avatar: getAvatar(4),
        tokenEarned: 5979,
        roi: 176,
        scholar: 800,
      },
      {
        id: 5,
        level: '5th',
        name: 'boeroe',
        avatar: getAvatar(5),
        tokenEarned: 5563,
        roi: 135,
        scholar: 500,
        scholarGuild: '/mock/guild/4.png',
      },
    ],
  },
  {
    id: 2,
    name: 'Stepn',
    logo: '/mock/game1/banner/logo_2.png',
    bg: '/mock/game/banner/bg_2.png',
    tokenLogo: '/mock/token/gst.webp',
    tokenName: 'GST',
    totalPrice: 25000,
    endTime: '2022-06-10 08:00:00',
    userList: [
      {
        id: 21,
        level: '1st',
        name: 'BADMAN',
        avatar: getAvatar(6),
        tokenEarned: 3258,
        roi: 271,
        scholar: 3000,
      },
      {
        id: 22,
        level: '2nd',
        name: 'cope',
        avatar: getAvatar(7),
        tokenEarned: 3219,
        roi: 266,
        scholar: 2500,
        scholarGuild: '/mock/guild/1.png',
      },
      {
        id: 23,
        level: '3rd',
        name: 'Miller',
        avatar: getAvatar(8),
        tokenEarned: 3061,
        roi: 259,
        scholar: 2000,
      },
      {
        id: 24,
        level: '4th',
        name: 'Sim010',
        avatar: getAvatar(9),
        tokenEarned: 3005,
        roi: 244,
        scholar: 1800,
        scholarGuild: '/mock/guild/2.png',
      },
      {
        id: 25,
        level: '5th',
        name: 'E7',
        avatar: getAvatar(10),
        tokenEarned: 2999,
        roi: 231,
        scholar: 1600,
        scholarGuild: '/mock/guild/1.png',
      },
    ],
  },
  {
    id: 3,
    name: 'Let me speak',
    logo: '/mock/game1/banner/logo_3.png',
    bg: '/mock/game/banner/bg_3.png',
    tokenLogo: '/mock/token/ls.png',
    tokenName: 'LS',
    totalPrice: 80000,
    endTime: '2022-06-10 18:00:00',
    userList: [
      {
        id: 31,
        level: '1st',
        name: 'BADMAN',
        avatar: getAvatar(11),
        tokenEarned: 3258,
        roi: 271,
        scholar: 9000,
        scholarGuild: '/mock/guild/3.png',
      },
      {
        id: 32,
        level: '2nd',
        name: 'cope',
        avatar: getAvatar(12),
        tokenEarned: 3219,
        roi: 266,
        scholar: 8000,
      },
      {
        id: 33,
        level: '3rd',
        name: 'Miller',
        avatar: getAvatar(13),
        tokenEarned: 3061,
        roi: 259,
        scholar: 7000,
        scholarGuild: '/mock/guild/4.png',
      },
      {
        id: 34,
        level: '4th',
        name: 'Sim010',
        avatar: getAvatar(14),
        tokenEarned: 3005,
        roi: 244,
        scholar: 5000,
      },
      {
        id: 35,
        level: '5th',
        name: 'E7',
        avatar: getAvatar(15),
        tokenEarned: 2999,
        roi: 209,
        scholar: 3000,
      },
    ],
  },
]

export const playerList = [
  {
    name: '0xCryptor',
    avatar: getAvatar(16),
    roi: 271,
    badge: ['/mock/badge/15.png', '/mock/badge/34.png', '/mock/badge/23.png'],
    devStatusLabel: statusDb[1],
    tags: [tagDb[2], tagDb[1], tagDb[3]],
  },
  {
    name: 'Christ',
    avatar: getAvatar(17),
    roi: 271,
    badge: ['/mock/badge/14.png', '/mock/badge/11.png', '/mock/badge/25.png'],
    devStatusLabel: statusDb[1],
    tags: [tagDb[12], tagDb[11]],
  },
  {
    name: 'Cliff',
    avatar: getAvatar(18),
    roi: 271,
    badge: ['/mock/badge/33.png', '/mock/badge/32.png', '/mock/badge/21.png'],
    devStatusLabel: statusDb[2],
    tags: [tagDb[3], tagDb[5], tagDb[6]],
  },
  {
    name: 'Dimok',
    avatar: getAvatar(19),
    roi: 271,
    badge: ['/mock/badge/14.png', '/mock/badge/25.png', '/mock/badge/31.png'],
    devStatusLabel: statusDb[3],
    tags: [tagDb[4], tagDb[5], tagDb[7]],
  },
  {
    name: 'DKOB',
    avatar: getAvatar(20),
    roi: 271,
    badge: ['/mock/badge/13.png', '/mock/badge/12.png', '/mock/badge/11.png'],
    devStatusLabel: statusDb[4],
    tags: [tagDb[2], tagDb[8], tagDb[9]],
  },
  {
    name: 'Guinox',
    avatar: getAvatar(21),
    roi: 271,
    badge: ['/mock/badge/24.png', '/mock/badge/32.png', '/mock/badge/25.png'],
    devStatusLabel: statusDb[3],
    tags: [tagDb[10], tagDb[2], tagDb[11]],
  },
  {
    name: 'harryho',
    avatar: getAvatar(22),
    roi: 271,
    badge: ['/mock/badge/24.png', '/mock/badge/13.png', '/mock/badge/14.png'],
    devStatusLabel: statusDb[2],
    tags: [tagDb[4], tagDb[9], tagDb[6]],
  },
  {
    name: 'Kustinski',
    avatar: getAvatar(23),
    roi: 271,
    badge: ['/mock/badge/14.png', '/mock/badge/23.png', '/mock/badge/32.png'],
    devStatusLabel: statusDb[4],
    tags: [tagDb[3], tagDb[6], tagDb[1]],
  },
]

export const playerList1 = [
  {
    id: 1,
    avatar: '/mock/player/1.png',
    name: 'Maximo YrysnkYrysnkYrysnk',
    roi: 134,
    tags: ['stable coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 2,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 3,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 4,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 5,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 6,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 7,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
  {
    id: 8,
    avatar: '/mock/player/1.png',
    name: 'Maximo Yrysnk',
    roi: 134,
    tags: ['Stable Coins', 'XSpend', 'Global'],
    medals: ['/mock/medal/4.png', '/mock/medal/6.png', '/mock/medal/8.png'],
  },
]

export const reviewList = [
  {
    gameName: 'Stepn',
    gameLogo: 'mock/game/1.jpg',
    text: 'We think the NFT-enabled, gamified, fitness-oriented move2earn mobile app that STEPN is building is an excellent idea. The additional monetary incentive alters the dopamine curve just enough to bring millions into healthier lifestyles and to the Web 3.0 world.',
    userName: 'Maple',
    userAvatar: getAvatar(24),
    userLevel: 2,
    startTime: '2022.03.21',
    likeCount: 367,
  },
  {
    gameName: 'Axie Infinity',
    gameLogo: 'mock/game/2.png',
    text: 'Axie Infinity is the perfect encapsulation of the future crypto wants: a crypto game so expensive to play, predatory lenders offer "scholarships" to those who can\'t afford it that requires they hand over a large percentage of their in-game earnings',
    userName: 'Binder',
    userAvatar: getAvatar(25),
    userLevel: 3,
    startTime: '2022.03.19',
    likeCount: 789,
  },
  {
    gameName: 'The Sandbox',
    gameLogo: 'mock/game/3.png',
    text: 'JUST IN: TIME Magazine has named The Sandbox #Metaverse one of the most influential companies of 2022.',
    userName: 'Guru',
    userAvatar: getAvatar(26),
    userLevel: 1,
    startTime: '2022.04.04',
    likeCount: 543,
  },
  {
    gameName: 'Decentraland',
    gameLogo: 'mock/game/4.jpeg', // 4
    text: 'wonderful project with great community. The leadership has been an inspiration in their innovative approaches towards achieving the project goals and visions.',
    userName: 'Hirok',
    userAvatar: getAvatar(27),
    userLevel: 3,
    startTime: '2022.05.12',
    likeCount: 863,
  },
  {
    gameName: 'My Neighbor Alice',
    gameLogo: 'mock/game/5.png', // 5
    text: 'The next animal crossing I believe, not as good as animal crossing but its a web3 game, keep going',
    userName: 'Artoria',
    userAvatar: getAvatar(28),
    userLevel: 2,
    startTime: '2022.05.21',
    likeCount: 296,
  },
  {
    gameName: 'Illuvium',
    gameLogo: 'mock/game/6.jpg', // 6
    text: "Love this. So excited to play. It's a really amazing experience to see a project in the works, before you play it. Kind of makes me feel part of it.",
    userName: 'Teloolan',
    userAvatar: getAvatar(29),
    userLevel: 1,
    startTime: '2022.01.21',
    likeCount: 385,
  },
]
export const reviewList1 = [
  {
    id: 1,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/1.png',
    userAvatar: '/mock/avatar/1.png',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
  {
    id: 2,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/3.png',
    userAvatar: '/mock/avatar/1.png',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
  {
    id: 3,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/1.png',
    userAvatar: '/mock/avatar/3.png',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
  {
    id: 4,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/2.png',
    userAvatar: '/mock/avatar/1.png',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
  {
    id: 5,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/1.png',
    userAvatar: '/mock/avatar/1.png',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
  {
    id: 6,
    gameName: 'Stepn',
    gameDesc: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. ',
    gameLogo: '/mock/game/1.png',
    userAvatar: '/mock/avatar/2.avif',
    userLevel: 2,
    userName: 'Maximo Yrysnk',
    startTime: '2022.01.21',
    followCount: 887,
  },
]
